---
version: '2'
volumes:
  postgre_apicurio:

services:
    # Schema Registry
  schema-registry:
    image: apicurio/apicurio-registry-sql:latest-snapshot
    restart: always
    ports:
      - "8080:8080"
    environment:
      REGISTRY_DATASOURCE_URL: "jdbc:postgresql://apicurio-db/apicuriodb"
      REGISTRY_DATASOURCE_USERNAME: "postgres"
      REGISTRY_DATASOURCE_PASSWORD: "postgres"
      SCHEMA_REGISTRY_HOST_NAME: schema-registry

  apicurio-db:
    ports:
      - '5432:5432'
    image: 'postgres:latest'
    environment:
      POSTGRES_DB: apicuriodb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - 'postgre_apicurio:/var/lib/postgresql/data'
    command:
      - "postgres"
      - "-c"
      - "wal_level=logical"
